#*****************************************************************************************
# Vivado (TM) v2023.1.1 (64-bit)
#
# project.tcl: Tcl script for re-creating project 'MznStrHrTdc'
#
# Generated by Vivado on Fri Apr 12 20:28:47 +0900 2024
# IP Build 3900379 on Sat Jun 17 05:28:05 MDT 2023
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/ip/clk_wiz_calib2/clk_wiz_calib2.xci"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/ip/clk_wiz_calib1/clk_wiz_calib1.xci"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/ip/clk_wiz_sys/clk_wiz_sys.xci"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/ip/clk_wiz_tdc/clk_wiz_tdc.xci"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/ip/sem_controller/sem_controller.xci"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/ip/xadc_sys/xadc_sys.xci"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/ip/ddr_oserdes/ddr_oserdes.xci"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/ip/ddr_oserdes_clk_fwd/ddr_oserdes_clk_fwd.xci"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/ip/mergerFrontFifo/mergerFrontFifo.xci"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/ip/incomingFifo/incomingFifo.xci"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/ip/dram_FineCountLUT/dram_FineCountLUT.xci"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/ip/finecount_bram/finecount_bram.xci"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/ip/scr_fifo/scr_fifo.xci"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/defBusAddressMap.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/common/bus_controller/defBusController.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/common/bct_bus_bridge/defBctBridge.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/common/main/synchronizer.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/common/main/ResetGen.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/common/bct_bus_bridge/BctBridgeSecondary.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/defHrTimingUnit.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/BinaryEncoder.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/common/sitcp/defRBCP.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/common/bus_controller/BusController.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/mikumari/cbt/defCDCM.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/mikumari/cbt/ClockMonitor.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/mikumari/cbt/CdcmTxEncoder.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/mikumari/cbt/CdcmTxImpl.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/mikumari/cbt/Cdcm8TxImpl.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/mikumari/cbt/CdcmTx.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/mikumari/cbt/CbtTx.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/mikumari/cbt/CdcmRxDecoder.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/mikumari/cbt/CdcmRxImpl.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/mikumari/cbt/Cdcm8RxImpl.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/mikumari/cbt/CdcmRx.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/mikumari/cbt/CbtRx.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/mikumari/cbt/CbtLane.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/hrtdc-impl/mezzanine/daq-support/ClkDivision3.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/hrtdc-impl/mezzanine/daq-support/defDAQController.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/hrtdc-impl/mezzanine/daq-support/DAQController.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/hrtdc-impl/mezzanine/daq-support/defDDRTransmitter.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/hrtdc-impl/mezzanine/daq-support/DataTransmitter.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/common/main/EdgeDetector.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/defFineCountLUT.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/FineCountLUT.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/utility/scaler/defFreeRunScaler.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/utility/scaler/FreeRunScaler.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/trigEmulation/defGateGen.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/laccp/utility/MyDPRamSE.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/trigEmulation/GateGen.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/LeadFinder.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/tdcClockDomainCrossing_v5.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/HRTimingDecoder.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/TappedDelayLineV2.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/RemappingTapsV3.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/HRTimingTaps.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/defDataBusAbst.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/laccp/laccp/defLaccp.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/laccp/laccp/defHeartBeatUnit.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/delimiter/defDelimiter.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/throttling/defThrottling.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/throttling/HbfThrottling.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/laccp/utility/MyDPRamSRRT.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/laccp/utility/MyDPRamDE.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/laccp/utility/MyFifoComClock.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/laccp/laccp/HeartBeatUnit.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/common/main/JKFF.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/laccp/laccp/defBitwiseOp.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/laccp/laccp/LaccpBusSwitch.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/mikumari/mikumari-link/defMikumari.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/laccp/laccp/LaccpFrameRx.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/laccp/laccp/LaccpFrameTx.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/laccp/laccp/RLIGP.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/laccp/laccp/RCAP.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/laccp/laccp/LaccpMainBlock.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/mikumari/mikumari-link/PRBS16.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/mikumari/mikumari-link/MikumariTx.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/mikumari/mikumari-link/MikumariRx.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/mikumari/mikumari-link/MikumariLane.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/mikumari/mikumari-link/Wrapper/MikumariBlock.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/common/bct_bus_bridge/defMznInterface.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/common/bct_bus_bridge/MznInterfaceS.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/throttling/OutputThrottling.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/common/main/defSelfDiagnosisSystem.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/common/mzn-impl/defSelfDiagnosisSystem.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/common/main/defSemImpl.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/common/main/SemImpl.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/common/mzn-impl/SelfDiagnosisSystem.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/hrtdc-impl/defTDC.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/odpblock/TOTFilter.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/common/sitcp/defSiTCP.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/odpblock/defTDCDelayBuffer.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/delimiter/DelimiterGenerator.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/odpblock/DelimiterInserter.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/vitalblock/IncomingBuffer.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/throttling/InputThrottlingType2.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/odpblock/LTMerger.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/odpblock/LTParing.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/vitalblock/MergerUnit.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/vitalblock/MergerBlock.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/vitalblock/MergerMznBlock.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/utility/mikumari/defMikumariUtil.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/utility/mikumari/MikumariUtil.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/odpblock/TDCDelayBuffer.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/ODPBlock.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/vitalblock/VitalBlock.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/hrtdc-impl/mezzanine/defStrHRTDC.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/strtdc/hrtdc-impl/mezzanine/strHrTdc.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/hdl/toplevel.vhd"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/constrs/pins.xdc"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/constrs/timing.xdc"
#    "C:/Xilinx/Vivado/vivado_project/amaneq-strtdc/MznStrHrTdc.git/constrs/impl.xdc"
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
 "[file normalize "$origin_dir/ip/clk_wiz_calib2/clk_wiz_calib2.xci"]"\
 "[file normalize "$origin_dir/ip/clk_wiz_calib1/clk_wiz_calib1.xci"]"\
 "[file normalize "$origin_dir/ip/clk_wiz_sys/clk_wiz_sys.xci"]"\
 "[file normalize "$origin_dir/ip/clk_wiz_tdc/clk_wiz_tdc.xci"]"\
 "[file normalize "$origin_dir/ip/sem_controller/sem_controller.xci"]"\
 "[file normalize "$origin_dir/ip/xadc_sys/xadc_sys.xci"]"\
 "[file normalize "$origin_dir/ip/ddr_oserdes/ddr_oserdes.xci"]"\
 "[file normalize "$origin_dir/ip/ddr_oserdes_clk_fwd/ddr_oserdes_clk_fwd.xci"]"\
 "[file normalize "$origin_dir/ip/mergerFrontFifo/mergerFrontFifo.xci"]"\
 "[file normalize "$origin_dir/ip/incomingFifo/incomingFifo.xci"]"\
 "[file normalize "$origin_dir/ip/dram_FineCountLUT/dram_FineCountLUT.xci"]"\
 "[file normalize "$origin_dir/ip/finecount_bram/finecount_bram.xci"]"\
 "[file normalize "$origin_dir/ip/scr_fifo/scr_fifo.xci"]"\
 "[file normalize "$origin_dir/hdl/defBusAddressMap.vhd"]"\
 "[file normalize "$origin_dir/hdl/common/bus_controller/defBusController.vhd"]"\
 "[file normalize "$origin_dir/hdl/common/bct_bus_bridge/defBctBridge.vhd"]"\
 "[file normalize "$origin_dir/hdl/common/main/synchronizer.vhd"]"\
 "[file normalize "$origin_dir/hdl/common/main/ResetGen.vhd"]"\
 "[file normalize "$origin_dir/hdl/common/bct_bus_bridge/BctBridgeSecondary.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/defHrTimingUnit.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/BinaryEncoder.vhd"]"\
 "[file normalize "$origin_dir/hdl/common/sitcp/defRBCP.vhd"]"\
 "[file normalize "$origin_dir/hdl/common/bus_controller/BusController.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/defCDCM.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/ClockMonitor.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/CdcmTxEncoder.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/CdcmTxImpl.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/Cdcm8TxImpl.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/CdcmTx.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/CbtTx.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/CdcmRxDecoder.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/CdcmRxImpl.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/Cdcm8RxImpl.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/CdcmRx.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/CbtRx.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/cbt/CbtLane.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/daq-support/ClkDivision3.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/daq-support/defDAQController.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/daq-support/DAQController.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/daq-support/defDDRTransmitter.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/daq-support/DataTransmitter.vhd"]"\
 "[file normalize "$origin_dir/hdl/common/main/EdgeDetector.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/defFineCountLUT.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/FineCountLUT.vhd"]"\
 "[file normalize "$origin_dir/hdl/utility/scaler/defFreeRunScaler.vhd"]"\
 "[file normalize "$origin_dir/hdl/utility/scaler/FreeRunScaler.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/trigEmulation/defGateGen.vhd"]"\
 "[file normalize "$origin_dir/hdl/laccp/utility/MyDPRamSE.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/trigEmulation/GateGen.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/LeadFinder.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/tdcClockDomainCrossing_v5.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/HRTimingDecoder.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/TappedDelayLineV2.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/RemappingTapsV3.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/HRTimingTaps.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/defDataBusAbst.vhd"]"\
 "[file normalize "$origin_dir/hdl/laccp/laccp/defLaccp.vhd"]"\
 "[file normalize "$origin_dir/hdl/laccp/laccp/defHeartBeatUnit.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/delimiter/defDelimiter.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/throttling/defThrottling.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/throttling/HbfThrottling.vhd"]"\
 "[file normalize "$origin_dir/hdl/laccp/utility/MyDPRamSRRT.vhd"]"\
 "[file normalize "$origin_dir/hdl/laccp/utility/MyDPRamDE.vhd"]"\
 "[file normalize "$origin_dir/hdl/laccp/utility/MyFifoComClock.vhd"]"\
 "[file normalize "$origin_dir/hdl/laccp/laccp/HeartBeatUnit.vhd"]"\
 "[file normalize "$origin_dir/hdl/common/main/JKFF.vhd"]"\
 "[file normalize "$origin_dir/hdl/laccp/laccp/defBitwiseOp.vhd"]"\
 "[file normalize "$origin_dir/hdl/laccp/laccp/LaccpBusSwitch.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/mikumari-link/defMikumari.vhd"]"\
 "[file normalize "$origin_dir/hdl/laccp/laccp/LaccpFrameRx.vhd"]"\
 "[file normalize "$origin_dir/hdl/laccp/laccp/LaccpFrameTx.vhd"]"\
 "[file normalize "$origin_dir/hdl/laccp/laccp/RLIGP.vhd"]"\
 "[file normalize "$origin_dir/hdl/laccp/laccp/RCAP.vhd"]"\
 "[file normalize "$origin_dir/hdl/laccp/laccp/LaccpMainBlock.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/mikumari-link/PRBS16.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/mikumari-link/MikumariTx.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/mikumari-link/MikumariRx.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/mikumari-link/MikumariLane.vhd"]"\
 "[file normalize "$origin_dir/hdl/mikumari/mikumari-link/Wrapper/MikumariBlock.vhd"]"\
 "[file normalize "$origin_dir/hdl/common/bct_bus_bridge/defMznInterface.vhd"]"\
 "[file normalize "$origin_dir/hdl/common/bct_bus_bridge/MznInterfaceS.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/throttling/OutputThrottling.vhd"]"\
 "[file normalize "$origin_dir/hdl/common/main/defSelfDiagnosisSystem.vhd"]"\
 "[file normalize "$origin_dir/hdl/common/mzn-impl/defSelfDiagnosisSystem.vhd"]"\
 "[file normalize "$origin_dir/hdl/common/main/defSemImpl.vhd"]"\
 "[file normalize "$origin_dir/hdl/common/main/SemImpl.vhd"]"\
 "[file normalize "$origin_dir/hdl/common/mzn-impl/SelfDiagnosisSystem.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/hrtdc-impl/defTDC.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/odpblock/TOTFilter.vhd"]"\
 "[file normalize "$origin_dir/hdl/common/sitcp/defSiTCP.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/odpblock/defTDCDelayBuffer.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/delimiter/DelimiterGenerator.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/odpblock/DelimiterInserter.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/vitalblock/IncomingBuffer.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/throttling/InputThrottlingType2.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/odpblock/LTMerger.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/odpblock/LTParing.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/vitalblock/MergerUnit.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/vitalblock/MergerBlock.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/vitalblock/MergerMznBlock.vhd"]"\
 "[file normalize "$origin_dir/hdl/utility/mikumari/defMikumariUtil.vhd"]"\
 "[file normalize "$origin_dir/hdl/utility/mikumari/MikumariUtil.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/odpblock/TDCDelayBuffer.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/ODPBlock.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/vitalblock/VitalBlock.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/defStrHRTDC.vhd"]"\
 "[file normalize "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/strHrTdc.vhd"]"\
 "[file normalize "$origin_dir/hdl/toplevel.vhd"]"\
 "[file normalize "$origin_dir/constrs/pins.xdc"]"\
 "[file normalize "$origin_dir/constrs/timing.xdc"]"\
 "[file normalize "$origin_dir/constrs/impl.xdc"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find remote file $ifile "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "MznStrHrTdc"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "project.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/build"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./build -part xc7k160tffg676-2

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "mylib" -objects $obj
set_property -name "enable_resource_estimation" -value "0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "disable" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xc7k160tffg676-2" -objects $obj
set_property -name "revised_directory_structure" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "sim_compile_state" -value "1" -objects $obj
set_property -name "target_language" -value "VHDL" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/ip/clk_wiz_calib2/clk_wiz_calib2.xci"] \
 [file normalize "${origin_dir}/ip/clk_wiz_calib1/clk_wiz_calib1.xci"] \
 [file normalize "${origin_dir}/ip/clk_wiz_sys/clk_wiz_sys.xci"] \
 [file normalize "${origin_dir}/ip/clk_wiz_tdc/clk_wiz_tdc.xci"] \
 [file normalize "${origin_dir}/ip/sem_controller/sem_controller.xci"] \
 [file normalize "${origin_dir}/ip/xadc_sys/xadc_sys.xci"] \
 [file normalize "${origin_dir}/ip/ddr_oserdes/ddr_oserdes.xci"] \
 [file normalize "${origin_dir}/ip/ddr_oserdes_clk_fwd/ddr_oserdes_clk_fwd.xci"] \
 [file normalize "${origin_dir}/ip/mergerFrontFifo/mergerFrontFifo.xci"] \
 [file normalize "${origin_dir}/ip/incomingFifo/incomingFifo.xci"] \
 [file normalize "${origin_dir}/ip/dram_FineCountLUT/dram_FineCountLUT.xci"] \
 [file normalize "${origin_dir}/ip/finecount_bram/finecount_bram.xci"] \
 [file normalize "${origin_dir}/ip/scr_fifo/scr_fifo.xci"] \
 [file normalize "${origin_dir}/hdl/defBusAddressMap.vhd"] \
 [file normalize "${origin_dir}/hdl/common/bus_controller/defBusController.vhd"] \
 [file normalize "${origin_dir}/hdl/common/bct_bus_bridge/defBctBridge.vhd"] \
 [file normalize "${origin_dir}/hdl/common/main/synchronizer.vhd"] \
 [file normalize "${origin_dir}/hdl/common/main/ResetGen.vhd"] \
 [file normalize "${origin_dir}/hdl/common/bct_bus_bridge/BctBridgeSecondary.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/defHrTimingUnit.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/BinaryEncoder.vhd"] \
 [file normalize "${origin_dir}/hdl/common/sitcp/defRBCP.vhd"] \
 [file normalize "${origin_dir}/hdl/common/bus_controller/BusController.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/defCDCM.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/ClockMonitor.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/CdcmTxEncoder.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/CdcmTxImpl.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/Cdcm8TxImpl.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/CdcmTx.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/CbtTx.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/CdcmRxDecoder.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/CdcmRxImpl.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/Cdcm8RxImpl.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/CdcmRx.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/CbtRx.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/cbt/CbtLane.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/hrtdc-impl/mezzanine/daq-support/ClkDivision3.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/hrtdc-impl/mezzanine/daq-support/defDAQController.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/hrtdc-impl/mezzanine/daq-support/DAQController.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/hrtdc-impl/mezzanine/daq-support/defDDRTransmitter.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/hrtdc-impl/mezzanine/daq-support/DataTransmitter.vhd"] \
 [file normalize "${origin_dir}/hdl/common/main/EdgeDetector.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/defFineCountLUT.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/FineCountLUT.vhd"] \
 [file normalize "${origin_dir}/hdl/utility/scaler/defFreeRunScaler.vhd"] \
 [file normalize "${origin_dir}/hdl/utility/scaler/FreeRunScaler.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/trigEmulation/defGateGen.vhd"] \
 [file normalize "${origin_dir}/hdl/laccp/utility/MyDPRamSE.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/trigEmulation/GateGen.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/LeadFinder.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/tdcClockDomainCrossing_v5.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/HRTimingDecoder.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/TappedDelayLineV2.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/RemappingTapsV3.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/HRTimingTaps.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/defDataBusAbst.vhd"] \
 [file normalize "${origin_dir}/hdl/laccp/laccp/defLaccp.vhd"] \
 [file normalize "${origin_dir}/hdl/laccp/laccp/defHeartBeatUnit.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/delimiter/defDelimiter.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/throttling/defThrottling.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/throttling/HbfThrottling.vhd"] \
 [file normalize "${origin_dir}/hdl/laccp/utility/MyDPRamSRRT.vhd"] \
 [file normalize "${origin_dir}/hdl/laccp/utility/MyDPRamDE.vhd"] \
 [file normalize "${origin_dir}/hdl/laccp/utility/MyFifoComClock.vhd"] \
 [file normalize "${origin_dir}/hdl/laccp/laccp/HeartBeatUnit.vhd"] \
 [file normalize "${origin_dir}/hdl/common/main/JKFF.vhd"] \
 [file normalize "${origin_dir}/hdl/laccp/laccp/defBitwiseOp.vhd"] \
 [file normalize "${origin_dir}/hdl/laccp/laccp/LaccpBusSwitch.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/mikumari-link/defMikumari.vhd"] \
 [file normalize "${origin_dir}/hdl/laccp/laccp/LaccpFrameRx.vhd"] \
 [file normalize "${origin_dir}/hdl/laccp/laccp/LaccpFrameTx.vhd"] \
 [file normalize "${origin_dir}/hdl/laccp/laccp/RLIGP.vhd"] \
 [file normalize "${origin_dir}/hdl/laccp/laccp/RCAP.vhd"] \
 [file normalize "${origin_dir}/hdl/laccp/laccp/LaccpMainBlock.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/mikumari-link/PRBS16.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/mikumari-link/MikumariTx.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/mikumari-link/MikumariRx.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/mikumari-link/MikumariLane.vhd"] \
 [file normalize "${origin_dir}/hdl/mikumari/mikumari-link/Wrapper/MikumariBlock.vhd"] \
 [file normalize "${origin_dir}/hdl/common/bct_bus_bridge/defMznInterface.vhd"] \
 [file normalize "${origin_dir}/hdl/common/bct_bus_bridge/MznInterfaceS.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/throttling/OutputThrottling.vhd"] \
 [file normalize "${origin_dir}/hdl/common/main/defSelfDiagnosisSystem.vhd"] \
 [file normalize "${origin_dir}/hdl/common/mzn-impl/defSelfDiagnosisSystem.vhd"] \
 [file normalize "${origin_dir}/hdl/common/main/defSemImpl.vhd"] \
 [file normalize "${origin_dir}/hdl/common/main/SemImpl.vhd"] \
 [file normalize "${origin_dir}/hdl/common/mzn-impl/SelfDiagnosisSystem.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/hrtdc-impl/defTDC.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/odpblock/TOTFilter.vhd"] \
 [file normalize "${origin_dir}/hdl/common/sitcp/defSiTCP.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/odpblock/defTDCDelayBuffer.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/delimiter/DelimiterGenerator.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/odpblock/DelimiterInserter.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/vitalblock/IncomingBuffer.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/throttling/InputThrottlingType2.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/odpblock/LTMerger.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/odpblock/LTParing.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/vitalblock/MergerUnit.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/vitalblock/MergerBlock.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/vitalblock/MergerMznBlock.vhd"] \
 [file normalize "${origin_dir}/hdl/utility/mikumari/defMikumariUtil.vhd"] \
 [file normalize "${origin_dir}/hdl/utility/mikumari/MikumariUtil.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/odpblock/TDCDelayBuffer.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/ODPBlock.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/vitalblock/VitalBlock.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/hrtdc-impl/mezzanine/defStrHRTDC.vhd"] \
 [file normalize "${origin_dir}/hdl/strtdc/hrtdc-impl/mezzanine/strHrTdc.vhd"] \
 [file normalize "${origin_dir}/hdl/toplevel.vhd"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/ip/clk_wiz_calib2/clk_wiz_calib2.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/ip/clk_wiz_calib1/clk_wiz_calib1.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/ip/clk_wiz_sys/clk_wiz_sys.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/ip/clk_wiz_tdc/clk_wiz_tdc.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/ip/sem_controller/sem_controller.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/ip/xadc_sys/xadc_sys.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/ip/ddr_oserdes/ddr_oserdes.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/ip/ddr_oserdes_clk_fwd/ddr_oserdes_clk_fwd.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/ip/mergerFrontFifo/mergerFrontFifo.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/ip/incomingFifo/incomingFifo.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/ip/dram_FineCountLUT/dram_FineCountLUT.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/ip/finecount_bram/finecount_bram.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/ip/scr_fifo/scr_fifo.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/hdl/defBusAddressMap.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/common/bus_controller/defBusController.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/common/bct_bus_bridge/defBctBridge.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/common/main/synchronizer.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/common/main/ResetGen.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/common/bct_bus_bridge/BctBridgeSecondary.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/defHrTimingUnit.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/BinaryEncoder.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/common/sitcp/defRBCP.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/common/bus_controller/BusController.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/defCDCM.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/ClockMonitor.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/CdcmTxEncoder.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/CdcmTxImpl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/Cdcm8TxImpl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/CdcmTx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/CbtTx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/CdcmRxDecoder.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/CdcmRxImpl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/Cdcm8RxImpl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/CdcmRx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/CbtRx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/cbt/CbtLane.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/daq-support/ClkDivision3.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/daq-support/defDAQController.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/daq-support/DAQController.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/daq-support/defDDRTransmitter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/daq-support/DataTransmitter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/common/main/EdgeDetector.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/defFineCountLUT.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/FineCountLUT.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/utility/scaler/defFreeRunScaler.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/utility/scaler/FreeRunScaler.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/trigEmulation/defGateGen.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/laccp/utility/MyDPRamSE.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/trigEmulation/GateGen.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/LeadFinder.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/tdcClockDomainCrossing_v5.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/HRTimingDecoder.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/TappedDelayLineV2.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/RemappingTapsV3.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/hrtdc/HRTimingTaps.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/defDataBusAbst.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/laccp/laccp/defLaccp.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/laccp/laccp/defHeartBeatUnit.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/delimiter/defDelimiter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/throttling/defThrottling.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/throttling/HbfThrottling.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/laccp/utility/MyDPRamSRRT.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/laccp/utility/MyDPRamDE.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/laccp/utility/MyFifoComClock.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/laccp/laccp/HeartBeatUnit.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/common/main/JKFF.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/laccp/laccp/defBitwiseOp.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/laccp/laccp/LaccpBusSwitch.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/mikumari-link/defMikumari.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/laccp/laccp/LaccpFrameRx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/laccp/laccp/LaccpFrameTx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/laccp/laccp/RLIGP.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/laccp/laccp/RCAP.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/laccp/laccp/LaccpMainBlock.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/mikumari-link/PRBS16.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/mikumari-link/MikumariTx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/mikumari-link/MikumariRx.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/mikumari-link/MikumariLane.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/mikumari/mikumari-link/Wrapper/MikumariBlock.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/common/bct_bus_bridge/defMznInterface.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/common/bct_bus_bridge/MznInterfaceS.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/throttling/OutputThrottling.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/common/main/defSelfDiagnosisSystem.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/common/mzn-impl/defSelfDiagnosisSystem.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/common/main/defSemImpl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/common/main/SemImpl.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/common/mzn-impl/SelfDiagnosisSystem.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/hrtdc-impl/defTDC.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/odpblock/TOTFilter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/common/sitcp/defSiTCP.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/odpblock/defTDCDelayBuffer.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/delimiter/DelimiterGenerator.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/odpblock/DelimiterInserter.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/vitalblock/IncomingBuffer.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/throttling/InputThrottlingType2.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/odpblock/LTMerger.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/odpblock/LTParing.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/vitalblock/MergerUnit.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/vitalblock/MergerBlock.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/vitalblock/MergerMznBlock.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/utility/mikumari/defMikumariUtil.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/utility/mikumari/MikumariUtil.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/odpblock/TDCDelayBuffer.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/odpblock/ODPBlock.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/vitalblock/VitalBlock.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/defStrHRTDC.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/strtdc/hrtdc-impl/mezzanine/strHrTdc.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

set file "$origin_dir/hdl/toplevel.vhd"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "dataflow_viewer_settings" -value "min_width=16" -objects $obj
set_property -name "top" -value "toplevel" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/constrs/pins.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/constrs/pins.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/constrs/timing.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/constrs/timing.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/constrs/impl.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/constrs/impl.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj
set_property -name "library" -value "mylib" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_part" -value "xc7k160tffg676-2" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Empty (no sources present)

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "toplevel" -objects $obj
set_property -name "top_lib" -value "mylib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]

set idrFlowPropertiesConstraints ""
catch {
 set idrFlowPropertiesConstraints [get_param runs.disableIDRFlowPropertyConstraints]
 set_param runs.disableIDRFlowPropertyConstraints 1
}

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7k160tffg676-2 -flow {Vivado Synthesis 2023} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2023" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "part" -value "xc7k160tffg676-2" -objects $obj
set_property -name "auto_incremental_checkpoint" -value "1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7k160tffg676-2 -flow {Vivado Implementation 2023} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2023" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "part" -value "xc7k160tffg676-2" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]
catch {
 if { $idrFlowPropertiesConstraints != {} } {
   set_param runs.disableIDRFlowPropertyConstraints $idrFlowPropertiesConstraints
 }
}

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1

# User-Tcl
source user-setting.tcl
exit